# Example config file for command-runner
# files: section allows you to specify complete files to be returned, together with optional processing.

# files:
#   - pathtofile: "/etc/hosts"    # Full Path to the File
#     monitor_tag: "etc hosts"    # Tag Name for Monitoring
#     keywords:                   # List of Keywords to Look for. If parseAll is set to true this is disregarded
#       - keyword1                # Line to parse that contains this keyword
#       - keyword2                # Line to parse that contains this keyword as well
#     parseAll: true              # Set this to true and parse the entire file. If false will only parse lines matching keywords
#     parsingLevel: server        # Setting to "server" will parse the entire. SDP "instance" will only run if p4d is installed
#     sanitizationKeywords:       # While parsing remove any of these lines containing these words - allows for removal of sensitive info
#       - C1A
#   - pathtofile: /p4/common/config/p4_%INSTANCE%.vars    # Where %INSTANCE% will replace the p4d SDP instance id.

files:
  # pathtofile: Full Path to the File
  #   Note: %INSTANCE% will be replaced by the p4d instance id.
  - pathtofile: "/etc/hosts"
    # monitor_tag: Tag Name for use in monitoring, e.g. by datapushgateway when it receives
    monitor_tag: "etc hosts"
    # keywords: Array/List of Keywords to search for. If parseAll is set to true this is disregarded.
    # Every specified keyword means that lines containing that word will be included
    keywords:
      - keyword1
      - keyword2
    # parseAll: Set this to true and parse the entire file. If false will only parse lines matching keywords
    parseAll: true
    # parsingLevel: Setting to "server" will parse the entire. "instance" will only run if p4d is installed
    parsingLevel: server
    # sanitizationKeywords: While parsing remove any of these lines containing these words - allows for removal of sensitive info
    #    Such as passwords or API tokens
    sanitizationKeywords:
      - C1A
  - pathtofile: /p4/common/config/p4_%INSTANCE%.vars
    monitor_tag: "p4 vars"
    keywords:
      - export MAILTO
      - export P4USER
      - export P4MASTER_ID
    parseAll: false
    parsingLevel: instance
    sanitizationKeywords:
      - sensitive
      - secret
  - pathtofile: "/p4/%INSTANCE%/root/license"
    monitor_tag: "license"
    keywords: []
    parseAll: true
    parsingLevel: instance
    sanitizationKeywords:
      - "License:"

# p4_commands: These are commands run against a p4d SDP instance (using bash, and sourcing SDP instance variables as appropriate)
p4_commands:
  - description: "p4 configure show allservers"
    command: "p4 configure show allservers"
    monitor_tag: "p4 configure"
  - description: "p4 triggers"
    command: "p4 triggers -o | awk '/^Triggers:/ {flag=1; next} /^$/ {flag=0} flag' | sed 's/^[ \\t]*//'"
    monitor_tag: "p4 triggers"
  - description: "p4 extensions and configs"
    command: "p4 extension --list --type extensions; p4 extension --list --type configs"
    monitor_tag: "p4 extensions"
  - description: "p4 servers"
    command: "p4 servers -J"
    monitor_tag: "p4 servers"
  - description: "p4 property -Al"
    command: "p4 property -Al"
    monitor_tag: "p4 property"
  - description: "p4 -Ztag Without the datefield?"
    command: "p4 -Ztag info | awk '!/^... (serverDate|serverUptime)/'"
    monitor_tag: "p4 ztag"
  - description: Swarm URL
    command: "p4 property -n P4.Swarm.URL -l 2>&1 | grep -v 'P4.Swarm.URL - no such property.' || true"
    monitor_tag: swarm url
  - description: Swarm URL v2
    command: "p4 property -n P4.Swarm.URL -l 2>&1"
    monitor_tag: swarm url


# os_commands (formerly server_commands): These are operating system commands (will be run using bash)
os_commands:
  - description: Server host information
    command: hostnamectl
    monitor_tag:  hostnamectl
  - description: Current active services
    command: systemctl --type=service --state=active
    monitor_tag: systemd
  - description: Current crontab -l
    command: crontab -l
    monitor_tag: crontab
  - description: Swarm Present on this server
    command: "[ -f /opt/perforce/swarm/Version ] && cat /opt/perforce/swarm/Version || true"
    monitor_tag: swarm here
  - description: SDP Version
    command: "[ -f /p4/sdp/Version ] && cat /p4/sdp/Version || true"
    monitor_tag: SDP Version
  - description: SDP Version v2
    command: "cat /p4/sdp/Version"
    monitor_tag: SDP Version
  - description: Command-Runner Version
    command: "/opt/perforce/command-runner/command-runner --version 2>&1"
    monitor_tag: Command-Runner Version