files:
  - pathtofile: "/etc/hosts"
    monitor_tag: "etc hosts"
    keywords:
      - keyword1
      - keyword2
    parseAll: true
    parsingLevel: server
    sanitizationKeywords:
      - C1A

  - pathtofile: /p4/common/config/p4_%INSTANCE%.vars
    monitor_tag: "p4 vars"
    keywords:
      - export MAILTO
      - export P4USER
      - export P4MASTER_ID
    parseAll: false
    parsingLevel: instance
    sanitizationKeywords:
      - sensitive
      - secret

  - pathtofile: "/etc/group"
    monitor_tag: "etc group"
    keywords:
      -
    parseAll: true
    parsingLevel: instance
    sanitizationKeywords:
      - landscape
